name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a las 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ItsBrutt
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git switch --create output || git switch output
          mkdir -p dist
          cp dist/* .
          git add github-contribution-grid-snake.svg*
          git commit -m "🐍 Generate GitHub Contribution Snake"
          git push origin output --force
